name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/aivideolab:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/aivideolab:latest

      - name: Make image public
        run: |
          PACKAGE_NAME="aivideolab"
          REPO_OWNER="${{ github.repository_owner }}"
          GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          PACKAGE_ID=$(gh api graphql -f query='
            query {
              repository(owner: "'$REPO_OWNER'", name: "aivideolab") {
                packages(first: 10, packageType: CONTAINER) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
          ' --jq '.data.repository.packages.nodes[] | select(.name=="'$PACKAGE_NAME'") | .id')

          echo "Found package ID: $PACKAGE_ID"

          gh api graphql -f query='
            mutation {
              changePackageVisibility(input: {
                packageId: "'$PACKAGE_ID'",
                visibility: PUBLIC
              }) {
                package {
                  name
                  visibility
                }
              }
            }
          '
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
