name: Make image public

on:
  workflow_dispatch:

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Get package ID
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PACKAGE_ID=$(gh api graphql -f query='
            query {
              repository(owner: "humanlaborunit", name: "Aivideolab") {
                packages(first: 1) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
          ' --jq '.data.repository.packages.nodes[0].id')

          echo "Found package ID: $PACKAGE_ID"
          echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV

      - name: Make image public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh api graphql -f query='
            mutation {
              changePackageVisibility(input: {
                packageId: "'${PACKAGE_ID}'",
                visibility: PUBLIC
              }) {
                package {
                  name
                  visibility
                }
              }
            }
          '

