name: Make image public

on:
  workflow_dispatch:

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: List packages and get package ID
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PACKAGE_NAME="aivideolab"
          PACKAGE_ID=$(gh api /user/packages/container/$PACKAGE_NAME/versions --jq '.[0].id')
          echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV

      - name: Make package version public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Making version $PACKAGE_ID public..."
          gh api --method PATCH /user/packages/container/aivideolab/versions/$PACKAGE_ID \
            -f visibility=public

