name: Make image public

on:
  workflow_dispatch:

jobs:
  make-public:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get package ID
        id: get_package_id
        run: |
          PACKAGE_ID=$(gh api graphql -f query='
            {
              repository(owner: "'${{ github.repository_owner }}'", name: "'${{ github.event.repository.name }}'") {
                packages(first: 10) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
          ' --jq '.data.repository.packages.nodes[0].id')
          echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV
          echo "Found package ID: $PACKAGE_ID"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make package public
        run: |
          gh api graphql -f query='
            mutation {
              changePackageVisibility(input: {
                packageId: "'${PACKAGE_ID}'",
                visibility: PUBLIC
              }) {
                package {
                  name
                  visibility
                }
              }
            }
          '
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_ID: ${{ env.PACKAGE_ID }}

