name: Make image public

on:
  workflow_dispatch:

jobs:
  make-public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get package ID
        id: get_id
        run: |
          PACKAGE_ID=$(gh api graphql -f query='
            query {
              repository(owner: "humanlaborunit", name: "Aivideolab") {
                packages(first: 1, packageType: CONTAINER) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
          ' --jq '.data.repository.packages.nodes[0].id')
          echo "Found package ID: $PACKAGE_ID"
          echo "PACKAGE_ID=$PACKAGE_ID" >> $GITHUB_ENV

      - name: Make package public
        run: |
          gh api graphql -f query='
            mutation {
              changePackageVisibility(input: {
                packageId: "'"$PACKAGE_ID"'",
                packageType: CONTAINER,
                visibility: PUBLIC
              }) {
                package {
                  name
                  visibility
                }
              }
            }
          '
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
