name: Build and Publish to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'launch.sh'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Make launch.sh executable ✅
      run: chmod +x launch.sh

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/aivideolab:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/aivideolab:latest

